kind: pipeline
type: exec
name: serhii-vysotskyi

steps:
  - name: Check installation Docker
    commands:
      - bash check_docker.sh

  - name: Check installation Docker Compose
    commands:
      - bash check_docker_compose.sh

  - name: test
    commands:
      - echo "Running tests"
