kind: pipeline
type: exec
name: serhii-vysotskyi

steps:
  - name: Check installation Docker
    commands:
      - bash check_docker.sh

  - name: Check installation Docker Compose
    commands:
      - bash check_docker_compose.sh
  
  - name: Stop all docker containers
    commands:
      - docker stop $(docker ps -a -q)
      - docker rm $(docker ps -a -q)
  
  - name: Remove all unused images
    commands:
      - docker image prune -a
  
  - name: Pull docker images
    commands:
      - docker pull nginx:latest

  - name: Start docker container
    commands:
      - docker run -d --name=web-server -p 80:80 nginx:latest
