kind: pipeline
type: exec
name: serhii-vysotskyi

steps:
  - name: Check installation Docker
    commands:
      - bash check_docker.sh

  - name: Check installation Docker Compose
    commands:
      - bash check_docker_compose.sh
  - name: Stop all docker containers
    commands:
      - 
  - name: Pull docker images
    commands:
      - docker pull nginx:1.27.2

  - name: Start docker container
    commands:
      - docker run -d --name=web-server -p 80:80 nginx:1.27.2
