kind: pipeline
type: exec
name: serhii-vysotskyi

steps:
  - name: setup
    commands:
      - if docker --version &> /dev/null; then
          echo "Docker is installed.";
        else
          echo "Docker is not installed. Start installation" && pwd;
        fi

  - name: build
    commands:
      - echo "Building the project"

  - name: test
    commands:
      - echo "Running tests"
