#Create test drone build
kind: pipeline
type: exec
name: serhii-vysotskyi

steps:
  - name: setup
    commands:
      - echo "Setting up the environment"

  - name: build
    commands:
      - echo "Building the project"
      - make build

  - name: test
    commands:
      - echo "Running tests"
      - make test
node:
  location: remote
